# Databricks notebook source
# MAGIC %md
# MAGIC ### Impulse — Ingest setup
# MAGIC Creates the status table and checkpoint volume needed by the ingest pipeline.
# MAGIC Idempotent (IF NOT EXISTS everywhere).

# COMMAND ----------

dbutils.widgets.text("catalog", "")
dbutils.widgets.text("schema", "")
dbutils.widgets.text("checkpoint_volume", "mdf4_checkpoint")

# COMMAND ----------

catalog = dbutils.widgets.get("catalog")
schema = dbutils.widgets.get("schema")
checkpoint_volume = dbutils.widgets.get("checkpoint_volume")

# Create silver schema + checkpoint volume (source volume already exists from upload)
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.{schema}")
spark.sql(f"CREATE VOLUME IF NOT EXISTS {catalog}.{schema}.{checkpoint_volume}")

spark.sql(f"""
  CREATE TABLE IF NOT EXISTS {catalog}.{schema}.status (
    container_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    run_id STRING,
    filename STRING,
    status STRING,
    _load_ts TIMESTAMP,
    _processing_done_ts TIMESTAMP
  )
""")

print(f"Setup complete: {catalog}.{schema}")
