"""Generate Impulse report code artifacts from ReportState.

Produces a single self-contained report notebook (no %run chains) and a config JSON.
"""

from __future__ import annotations

import json
from typing import Any

from server.models import Histogram1DDefinition, Histogram2DDefinition, HistogramType, ReportState, StatisticsDefinition


# Map HistogramType enum to framework agg_type string
_HISTOGRAM_AGG_TYPE_MAP = {
    HistogramType.DURATION: "duration",
    HistogramType.DISTANCE: "distance",
    HistogramType.DURATION_COUNT: "duration_count",
    HistogramType.EVENT_COUNT: "event_count",
}


def _cmd() -> str:
    return "# COMMAND ----------"


def generate_report_notebook(state: ReportState) -> str:
    """Generate a single self-contained report notebook.

    Contains: imports, report init, signal definitions, aggregations,
    determine_report(), and persist_results() — all inline, no %run calls.
    """
    lines: list[str] = []

    # --- Header ---
    lines += [
        "# Databricks notebook source",
        "# MAGIC %md",
        f"# MAGIC # {state.name}",
        f"# MAGIC {state.description or 'Auto-generated by Impulse.'}",
        "",
        _cmd(),
        "",
    ]

    # --- Imports & setup ---
    lines += [
        "import sys, os, json",
        "from datetime import datetime",
        "",
        'base_path = os.path.dirname(os.path.abspath("__file__"))',
        "base_path = base_path[:base_path.find('src')]",
        'sys.path.append(f"{base_path}/src/")',
        "",
        'spark.conf.set("spark.sql.shuffle.partitions", "auto")',
        "",
        "from mda_reporting.core.report import Report",
        "from mda_reporting.core.page import Page",
        "from mda_reporting.aggregations.histogram import Histogram",
        "from mda_reporting.aggregations.histogram2d import Histogram2D",
        "from mda_reporting.aggregations.statistics import Statistics",
        "from mda_reporting.events.basic_event import BasicEvent",
        "",
        _cmd(),
        "",
    ]

    # --- Config & report init ---
    lines += [
        "# MAGIC %md",
        "# MAGIC ## Initialize Report",
        "",
        _cmd(),
        "",
        'dbutils.widgets.text("config_path", "./config/dev_config.json")',
        'config_path = dbutils.widgets.get("config_path")',
        "print(f\"Config: {config_path}\")",
        "",
        'my_report = Report(name="report", spark=spark, config_path=config_path)',
        "query = my_report.query",
        "print(f\"Report initialized: {my_report.config.unity_sink.catalog}.{my_report.config.unity_sink.schema}.{my_report.config.unity_sink.table_prefix}\")",
        "",
        _cmd(),
        "",
    ]

    # --- Signal definitions ---
    lines += [
        "# MAGIC %md",
        "# MAGIC ## Signal Definitions",
        "",
        _cmd(),
        "",
    ]

    physical = [s for s in state.signals if s.signal_type == "physical"]
    virtual = [s for s in state.signals if s.signal_type == "virtual"]

    for sig in physical:
        ch_name = sig.channel_name or sig.alias or sig.var_name
        desc = f"  # {sig.description}" if sig.description else ""
        lines.append(f'{sig.var_name} = query.channel(channel_name="{ch_name}"){desc}')

    if physical and virtual:
        lines += ["", _cmd(), ""]

    for sig in virtual:
        desc = f"  # {sig.description}" if sig.description else ""
        lines.append(f"{sig.var_name} = {sig.expression}{desc}")

    lines += [
        "",
        "signals = {",
    ]
    for sig in state.signals:
        lines.append(f'    "{sig.var_name}": {sig.var_name},')
    lines += [
        "}",
        f'print(f"Defined {{len(signals)}} signals: {{list(signals.keys())}}")',
        "",
        _cmd(),
        "",
    ]

    # --- Aggregations ---
    lines += [
        "# MAGIC %md",
        "# MAGIC ## Aggregations",
        "",
        _cmd(),
        "",
        "page = Page(page_number=1)",
        "my_report.add_page(page)",
        "",
    ]

    # 1D histograms
    histograms_1d = [a for a in state.aggregations if isinstance(a, Histogram1DDefinition)]
    for hist in histograms_1d:
        lines += [_cmd(), ""]
        agg_type = _HISTOGRAM_AGG_TYPE_MAP[hist.histogram_type]

        params = [
            f'    name="{hist.name}"',
            f'    base_expr=signals["{hist.signal_ref}"]',
            f"    bins={hist.bins}",
        ]
        if hist.histogram_type == HistogramType.EVENT_COUNT and hist.event_signal_ref:
            params.append(f'    event=BasicEvent(name="{hist.name}_event", expr=signals["{hist.event_signal_ref}"])')
        if hist.description:
            params.append(f'    desc="{hist.description}"')
        params.append(f'    agg_type="{agg_type}"')
        if hist.bins_unit:
            params.append(f'    bins_unit="{hist.bins_unit}"')
        if hist.values_unit:
            params.append(f'    values_unit="{hist.values_unit}"')

        lines.append("hist = Histogram(")
        lines.append(",\n".join(params) + ",")
        lines.append(")")
        lines.append("page.add_aggregation(hist)")
        lines.append(f'print(f"Added 1D histogram: {hist.name}")')
        lines.append("")

    # 2D histograms
    histograms_2d = [a for a in state.aggregations if isinstance(a, Histogram2DDefinition)]
    for hist2d in histograms_2d:
        lines += [_cmd(), ""]

        params = [
            f'    name="{hist2d.name}"',
            f'    x_expr=signals["{hist2d.x_signal_ref}"]',
            f'    y_expr=signals["{hist2d.y_signal_ref}"]',
            f"    x_bins={hist2d.x_bins}",
            f"    y_bins={hist2d.y_bins}",
        ]
        if hist2d.description:
            params.append(f'    desc="{hist2d.description}"')
        if hist2d.x_bins_unit:
            params.append(f'    x_bins_unit="{hist2d.x_bins_unit}"')
        if hist2d.y_bins_unit:
            params.append(f'    y_bins_unit="{hist2d.y_bins_unit}"')
        if hist2d.values_unit:
            params.append(f'    values_unit="{hist2d.values_unit}"')

        lines.append("hist2d = Histogram2D(")
        lines.append(",\n".join(params) + ",")
        lines.append(")")
        lines.append("page.add_aggregation(hist2d)")
        lines.append(f'print(f"Added 2D histogram: {hist2d.name}")')
        lines.append("")

    # Statistics
    statistics = [a for a in state.aggregations if isinstance(a, StatisticsDefinition)]
    for stats in statistics:
        lines += [_cmd(), ""]

        selections_items = ", ".join(f'signals["{ref}"]' for ref in stats.signal_refs)
        labels_repr = repr(stats.stat_labels)

        params = [
            f'    name="{stats.name}"',
            f"    selections=[{selections_items}]",
            f"    aggregation_labels={labels_repr}",
        ]
        if stats.event_signal_ref:
            params.append(f'    event=BasicEvent(name="{stats.name}_event", expr=signals["{stats.event_signal_ref}"])')
        if stats.description:
            params.append(f'    desc="{stats.description}"')

        lines.append("stat = Statistics(")
        lines.append(",\n".join(params) + ",")
        lines.append(")")
        lines.append("page.add_aggregation(stat)")
        lines.append(f'print(f"Added statistics: {stats.name}")')
        lines.append("")

    # --- Execute report ---
    lines += [
        _cmd(),
        "",
        "# MAGIC %md",
        "# MAGIC ## Execute Report",
        "",
        _cmd(),
        "",
        'print(f"[{datetime.now().isoformat()}] Starting determine_report()...")',
        "my_report.determine_report()",
        'print(f"[{datetime.now().isoformat()}] determine_report() complete.")',
        "",
        _cmd(),
        "",
        'print(f"[{datetime.now().isoformat()}] Starting persist_results()...")',
        "my_report.persist_results()",
        'print(f"[{datetime.now().isoformat()}] persist_results() complete. Report done.")',
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# dev_config.json
# ---------------------------------------------------------------------------

def generate_config_json(state: ReportState) -> dict[str, Any]:
    ds = state.data_sources

    units_under_test = []
    for v in state.vehicles:
        entry: dict[str, Any] = {
            "uut_name": {"col_name": v.col_name, "value": v.vehicle_id},
            "start_ts": {
                "col_name": "start_dt",
                "value": v.start_ts,
            },
        }
        if v.stop_ts:
            entry["end_ts"] = {
                "col_name": "stop_dt",
                "value": v.stop_ts,
            }
        units_under_test.append(entry)

    source: dict[str, Any] = {
        "container_metrics_table": ds.container_metrics,
        "channel_metrics_table": ds.channel_metrics,
        "channels_table": ds.channels[0] if ds.channels else "",
        "container_tags_table": ds.container_tags,
        "channel_tags_table": ds.channel_tags,
    }

    return {
        "source": source,
        "unity_sink": {
            "catalog": ds.destination_catalog,
            "schema": ds.destination_schema,
            "table_prefix": ds.table_prefix or f"{state.name}_report",
        },
        "units_under_test": units_under_test,
        "query_engine": {
            "solver": "DeltaSolver",
            "data_type": "RLE",
            "drop_implausible_data": False,
        },
        "measurement_dimensions": [
            "container_id",
            "vehicle_key",
            "start_ts",
            "stop_ts",
        ],
    }


def generate_all_files(state: ReportState) -> dict[str, str]:
    """Return a dict mapping relative file paths to their content."""
    return {
        "src/report.py": generate_report_notebook(state),
        "src/config/dev_config.json": json.dumps(generate_config_json(state), indent=2),
    }
