"""Generate Impulse report code artifacts from ReportState.

Code patterns are taken directly from the define-channels and create-histogram-1d skills.
"""

from __future__ import annotations

import json
from typing import Any

from server.models import Histogram1DDefinition, Histogram2DDefinition, HistogramType, ReportState, StatisticsDefinition


# ---------------------------------------------------------------------------
# 01_signal_definitions.py  (define-channels skill step 5)
# ---------------------------------------------------------------------------

def generate_signal_definitions(state: ReportState) -> str:
    lines = [
        "# Databricks notebook source",
        "# MAGIC %md",
        "# MAGIC ##### Signal Definitions",
        "# MAGIC",
        "# MAGIC Auto-generated by Impulse.",
        "",
        "# COMMAND ----------",
        "",
    ]

    physical = [s for s in state.signals if s.signal_type == "physical"]
    virtual = [s for s in state.signals if s.signal_type == "virtual"]

    if physical:
        lines.append("# Physical channels")
        for sig in physical:
            desc = f"  # {sig.description}" if sig.description else ""
            # Use channel_name for direct silver layer lookup;
            # fall back to alias for legacy alias-based setups
            ch_name = sig.channel_name or sig.alias or sig.var_name
            lines.append(
                f'{sig.var_name} = query.channel('
                f'channel_name="{ch_name}"){desc}'
            )
        lines.append("")
        lines.append("# COMMAND ----------")
        lines.append("")

    if virtual:
        lines.append("# Virtual / derived signals")
        for sig in virtual:
            desc = f"  # {sig.description}" if sig.description else ""
            lines.append(f"{sig.var_name} = {sig.expression}{desc}")
        lines.append("")
        lines.append("# COMMAND ----------")
        lines.append("")

    lines.append("# Signals dictionary for access by aggregations")
    lines.append("signals = {")
    for sig in state.signals:
        lines.append(f'    "{sig.var_name}": {sig.var_name},')
    lines.append("}")
    lines.append("")
    lines.append("# Make all variables available in the global scope")
    lines.append("globals().update(locals())")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Histogram page  (create-histogram-1d skill step 5)
# ---------------------------------------------------------------------------

# Map HistogramType enum to framework agg_type string
_HISTOGRAM_AGG_TYPE_MAP = {
    HistogramType.DURATION: "duration",
    HistogramType.DISTANCE: "distance",
    HistogramType.DURATION_COUNT: "duration_count",
    HistogramType.EVENT_COUNT: "event_count",
}


def generate_histogram_page(state: ReportState) -> str:
    lines = [
        "# Databricks notebook source",
        "# MAGIC %md",
        "# MAGIC ##### Histogram Aggregations",
        "# MAGIC",
        "# MAGIC Auto-generated by Impulse.",
        "",
        "# COMMAND ----------",
        "",
        "my_first_page = Page(page_number=1)",
        "my_report.add_page(my_first_page)",
        "",
    ]

    histograms_1d = [a for a in state.aggregations if isinstance(a, Histogram1DDefinition)]
    for hist in histograms_1d:
        lines.append("# COMMAND ----------")
        lines.append("")

        agg_type = _HISTOGRAM_AGG_TYPE_MAP[hist.histogram_type]
        lines.append(f"# MAGIC %md")
        lines.append(f"# MAGIC ##### {hist.description or hist.name}")
        lines.append("")
        lines.append("# COMMAND ----------")
        lines.append("")

        params = [
            f'    name="{hist.name}"',
            f'    base_expr=signals["{hist.signal_ref}"]',
            f"    bins={hist.bins}",
        ]

        if hist.histogram_type == HistogramType.EVENT_COUNT and hist.event_signal_ref:
            params.append(f'    event=BasicEvent(name="{hist.name}_event", expr=signals["{hist.event_signal_ref}"])')

        if hist.description:
            params.append(f'    desc="{hist.description}"')
        params.append(f'    agg_type="{agg_type}"')
        if hist.bins_unit:
            params.append(f'    bins_unit="{hist.bins_unit}"')
        if hist.values_unit:
            params.append(f'    values_unit="{hist.values_unit}"')

        lines.append(f"hist = Histogram(")
        lines.append(",\n".join(params) + ",")
        lines.append(")")
        lines.append("my_first_page.add_aggregation(hist)")
        lines.append("")

    # 2D histograms
    histograms_2d = [a for a in state.aggregations if isinstance(a, Histogram2DDefinition)]
    for hist2d in histograms_2d:
        lines.append("# COMMAND ----------")
        lines.append("")
        lines.append("# MAGIC %md")
        lines.append(f"# MAGIC ##### {hist2d.description or hist2d.name}")
        lines.append("")
        lines.append("# COMMAND ----------")
        lines.append("")

        params = [
            f'    name="{hist2d.name}"',
            f'    x_expr=signals["{hist2d.x_signal_ref}"]',
            f'    y_expr=signals["{hist2d.y_signal_ref}"]',
            f"    x_bins={hist2d.x_bins}",
            f"    y_bins={hist2d.y_bins}",
        ]
        if hist2d.description:
            params.append(f'    desc="{hist2d.description}"')
        if hist2d.x_bins_unit:
            params.append(f'    x_bins_unit="{hist2d.x_bins_unit}"')
        if hist2d.y_bins_unit:
            params.append(f'    y_bins_unit="{hist2d.y_bins_unit}"')
        if hist2d.values_unit:
            params.append(f'    values_unit="{hist2d.values_unit}"')

        lines.append("hist2d = Histogram2D(")
        lines.append(",\n".join(params) + ",")
        lines.append(")")
        lines.append("my_first_page.add_aggregation(hist2d)")
        lines.append("")

    # Statistics aggregations
    statistics = [a for a in state.aggregations if isinstance(a, StatisticsDefinition)]
    for stats in statistics:
        lines.append("# COMMAND ----------")
        lines.append("")
        lines.append("# MAGIC %md")
        lines.append(f"# MAGIC ##### {stats.description or stats.name}")
        lines.append("")
        lines.append("# COMMAND ----------")
        lines.append("")

        selections_items = ", ".join(f'signals["{ref}"]' for ref in stats.signal_refs)
        labels_repr = repr(stats.stat_labels)

        params = [
            f"    name=\"{stats.name}\"",
            f"    selections=[{selections_items}]",
            f"    aggregation_labels={labels_repr}",
        ]
        if stats.event_signal_ref:
            params.append(f'    event=BasicEvent(name="{stats.name}_event", expr=signals["{stats.event_signal_ref}"])')
        if stats.description:
            params.append(f'    desc="{stats.description}"')

        lines.append("stat = Statistics(")
        lines.append(",\n".join(params) + ",")
        lines.append(")")
        lines.append("my_first_page.add_aggregation(stat)")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Chapter orchestrator
# ---------------------------------------------------------------------------

def generate_orchestrator(state: ReportState) -> str:
    return "\n".join([
        "# Databricks notebook source",
        "# MAGIC %md",
        f"# MAGIC # {state.description or state.name}",
        "# MAGIC Auto-generated by Impulse.",
        "",
        '# COMMAND ----------',
        "",
        '# MAGIC %run "./pages/01_histograms"',
    ])


# ---------------------------------------------------------------------------
# dev_config.json  (configure-report skill)
# ---------------------------------------------------------------------------

def generate_config_json(state: ReportState) -> dict[str, Any]:
    ds = state.data_sources

    # Build units_under_test from vehicle config
    units_under_test = []
    for v in state.vehicles:
        entry: dict[str, Any] = {
            "uut_name": {"col_name": v.col_name, "value": v.vehicle_id},
            "start_ts": {
                "col_name": "start_dt",
                "value": v.start_ts,
            },
        }
        if v.stop_ts:
            entry["end_ts"] = {
                "col_name": "stop_dt",
                "value": v.stop_ts,
            }
        units_under_test.append(entry)

    # Build source config — use 3-part UC table names
    source: dict[str, Any] = {
        "container_metrics_table": ds.container_metrics,
        "channel_metrics_table": ds.channel_metrics,
        "channels_table": ds.channels[0] if ds.channels else "",
    }

    return {
        "source": source,
        "unity_sink": {
            "catalog": ds.destination_catalog,
            "schema": ds.destination_schema,
            "table_prefix": ds.table_prefix or f"{state.name}_report",
        },
        "units_under_test": units_under_test,
        "query_engine": {
            "solver": "BasicNarrowSolver",
            "data_type": "RLE",
            "drop_implausible_data": False,
        },
        "measurement_dimensions": [
            "container_id",
            "vehicle_key",
            "start_ts",
            "stop_ts",
        ],
    }


def generate_all_files(state: ReportState) -> dict[str, str]:
    """Return a dict mapping relative file paths to their content."""
    return {
        "src/01_signal_definitions.py": generate_signal_definitions(state),
        "src/chapters/01_chapter/pages/01_histograms.py": generate_histogram_page(state),
        "src/chapters/01_chapter/orchestrator.py": generate_orchestrator(state),
        "src/config/dev_config.json": json.dumps(generate_config_json(state), indent=2),
    }
